Repository microsoft/mu_crypto_release, pull requests merged in 2024-12, with the labels that each got.

#114 Fix OpensslPkg CI
  OpensslPkg/Library/HmacSha1Lib/HmacSha1Lib.inf
  OpensslPkg/Library/IntrinsicLib/IntrinsicLib.inf
  OpensslPkg/OpensslPkg.ci.yaml
  OpensslPkg/OpensslPkg.dec
  OpensslPkg/OpensslPkg.dsc
Labels: impact:non-functional, type:bug

#115 Update instructions for semantic versioning
  .azuredevops/pipelines/ReleaseBuild.yml
  CryptoBinPkg/Driver/readme.md
Labels: impact:non-functional, type:documentation, type:feature-request

#117 Correct checks for StMm and Stmm_Supv conflicts.
  CryptoBinPkg/Driver/Packaging/generate_cryptodriver.py
Labels: impact:non-functional, language:python
